### ISSUE TITLE
Fuse Integration: SwitchYard: Knowledge Common Component Library  FAILURE

### ISSUE THREAD

**Issue by mbiarnes** [jboss-integration/fuse-bxms-integ#145]
I tried to execute prefectus/fuse-bxms-integ-1.1.x-release.sh on JENKINS to generate a tag for productusation for the integ pack and I get:
https://10.8.63.16/view/Fuse%20Integration/job/perfectus-fuse-integration-1.1.x/22/console
(compilation error)

**Comment by dvirgiln** [comment]
Hi mbiarnes.

I know this error. This error is coming from drools. We overload a class from drools. 

I ve tried the 1.1.x branch, that uses the drools 6.2.x branch and it is working perfectly.

@mariofusco can you help us here?

**Comment by mbiarnes** [comment]
thanx dvirgiln -
I think the error is then in 6.3.x vs 6.2.x - as in the script it is used the 6.3.x  - branch of drools -
the 6.3.0.Final-redhat-1 version.

**Comment by dvirgiln** [comment]
but the 1.1.x code is compatible with drools 6.2.x

**Comment by mbiarnes** [comment]
this means we can't build a tag for fuse-bxms-integ using the fuse-bxms-integ-1.1.x-release.sh and 6.3.0.Final-redhat-1 ?

**Comment by dvirgiln** [comment]
We need to know which is the version of drools we want to use with the fuse
bxms integ 1.1.x branch. Until now the drools version used in this branch
has been 6.2.x. in case we want to use 6.3.x we nedd to include easy
changes in the 1.1.x branch.

Our master code is 6.3.x compatibe and the changes between 1.1.x and master
are minimal

**Comment by psiroky** [comment]
I believe we need a new branch. We need to support both 6.2.x and 6.3.x versions of KIE.

@dvirgiln I see you already created branch 1.2.x, is this the one which will use KIE 6.3.x?

**Comment by psiroky** [comment]
Closing, this is outdated.
